name: nix
on:
  push:
    branches:
      - main
    paths:
      - "*.nix"
      - "**/*.nix"
      - "Cargo.lock"
      - "flake.lock"
  pull_request:
    branches:
      - main
    paths:
      - "*.nix"
      - "**/*.nix"
      - "Cargo.lock"
      - "flake.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  alejandra:
    runs-on: ubuntu-26.04
    name: alejandra
    if: github.actor != 'renovate[bot]'
    steps:
      - name: harden_runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            cache.nixos.org:443
            cachix.org:443
            github.com:443
            purpleclay.cachix.org:443
            releases.nixos.org:443
            static.rust-lang.org:443

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: install_nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: setup_cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: run_alejandra
        run: nix develop -c alejandra --check .

  build:
    runs-on: ${{ matrix.os }}
    name: build_${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-15]
    steps:
      - name: harden_runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: block
          allowed-endpoints: >
            6d63fbac34f30fbde4e3420ca14565c0.r2.cloudflarestorage.com:443
            api.github.com:443
            cache.nixos.org:443
            cachix.org:443
            github.com:443
            purpleclay.cachix.org:443
            releases.nixos.org:443
            static.crates.io:443
            static.rust-lang.org:443

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: install_nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: setup_cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: false
          useDaemon: false

      - name: build_nix_package
        run: nix build
