name: typos
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  typos:
    runs-on: ubuntu-26.04
    if: github.actor != 'renovate[bot]'
    name: check_spelling
    steps:
      - name: harden_runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            cache.nixos.org:443
            cachix.org:443
            github.com:443
            purpleclay.cachix.org:443
            releases.nixos.org:443
            static.rust-lang.org:443

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: install_nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup_cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: run_typos
        run: nix develop -c typos
